"""Core implementation for RFC 5322 compliant Message-ID generation.

Per RFC 5322 §3.6.4, a Message-ID has the form `<local-part@domain>`.
RFC 5322 §3.2.3 defines the atom structure for local-parts.

The local part is generated by hashing the sha256 of:
    domain | process-id | monotonic-counter | clock-tick

This combination guarantees uniqueness across processes, across ticks, and
within a single tick (via the counter). The local part is truncated to
64 hex characters, well within RFC 5321's 64-octet local-part limit.

Edge cases handled:
  - Clock going backwards: detection raises ClockMovedBackwards so the
    caller can decide policy rather than silently emitting duplicates.
  - Clock equal to previous tick: the counter advances, so ids remain
    unique within the same tick.
  - Domain containing non-atom characters: ValueError raised at construction
    so generation never emits a non-compliant Message-ID.
"""
from __future__ import annotations

import hashlib
import os
import re
import threading
from typing import Callable, Optional

# atext per RFC 5322 §3.2.3, restricted to printable ASCII safe for local-parts.
_ATEXT = re.compile(r"[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+")
_DOMAIN_CHARS = re.compile(r"[A-Za-z0-9](?:[A-Za-z0-9.-]*[A-Za-z0-9])?")


class ClockMovedBackwards(RuntimeError):
    """Raised when the supplied clock returns an earlier tick than a prior one.

    Detecting this lets callers choose policy (reset, abort, or log) instead
    of silently producing values that could collide with earlier output.
    """


class MessageIdGenerator:
    """Generates globally-unique, RFC 5322 compliant Message-ID headers.

    Parameters
    ----------
    domain:
        Fully-qualified domain that will appear after '@'. Must consist of
        letters, digits, dots, or hyphens; must start and end with a letter
        or digit. This is a subset of RFC 5322 domain-literal rules that
        remains safe across SMTP implementations.
    clock:
        Optional callable returning a monotonic non-decreasing integer tick.
        Injecting the clock makes tests deterministic and lets callers use
        a real monotonic source in production. If omitted, a default based
        on time.monotonic_ns is used.
    """

    _MAX_LOCAL_PART_LEN = 64
    _HASH_HEX_LEN = 64

    def __init__(
        self,
        domain: str,
        clock: Optional[Callable[[], int]] = None,
    ) -> None:
        if not isinstance(domain, str) or not domain:
            raise ValueError("domain must be a non-empty string")
        if not _DOMAIN_CHARS.fullmatch(domain):
            raise ValueError(
                "domain must start and end with a letter or digit and contain "
                "only letters, digits, dots, or hyphens"
            )
        if clock is None:
            import time

            clock = time.monotonic_ns
        self._domain = domain
        self._clock = clock
        self._counter = 0
        self._last_tick: Optional[int] = None
        self._lock = threading.Lock()
        self._pid = os.getpid()

    def generate(self) -> str:
        """Return a new Message-ID string of the form `<local@domain>`."""
        with self._lock:
            tick = int(self._clock())
            if self._last_tick is not None and tick < self._last_tick:
                raise ClockMovedBackwards(
                    f"clock tick {tick} precedes previous {self._last_tick}"
                )
            if self._last_tick is None or tick != self._last_tick:
                self._counter = 0
                self._last_tick = tick
            seq = self._counter
            self._counter += 1

        # Hash components together to produce an unguessable, unique digest.
        material = f"{self._domain}|{self._pid}|{tick}|{seq}".encode("ascii")
        digest = hashlib.sha256(material).hexdigest()[: self._HASH_HEX_LEN]
        return f"<{digest}@{self._domain}>"


def generate_message_id(domain: str, clock: Optional[Callable[[], int]] = None) -> str:
    """Convenience function: returns a single Message-ID for *domain*.

    This constructs a transient MessageIdGenerator. For high-throughput use,
    prefer instantiating MessageIdGenerator once and calling .generate() per
    message, so the per-call counter advances without re-initializing.
    """
    return MessageIdGenerator(domain, clock=clock).generate()
